"""upgrade piece model 3

Revision ID: 215917110b8c
Revises: 144d18a609ec
Create Date: 2022-08-03 18:43:02.302842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215917110b8c'
down_revision = '144d18a609ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('tweet_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'tweet_id')
    # ### end Alembic commands ###
