"""pieces_and_participant_initial_models

Revision ID: 42fc0ab5fbbe
Revises: 
Create Date: 2022-08-02 23:26:09.728090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fc0ab5fbbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('profile_url', sa.String(length=300), nullable=False),
    sa.Column('affiliated_party', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('piece',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('input_original', sa.String(length=300), nullable=False),
    sa.Column('input_translated', sa.String(length=300), nullable=True),
    sa.Column('tweet_url', sa.String(length=300), nullable=False),
    sa.Column('tweet_comments', sa.Integer(), nullable=False),
    sa.Column('tweet_likes', sa.Integer(), nullable=False),
    sa.Column('artifact_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_username', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['account_username'], ['participant.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piece')
    op.drop_table('participant')
    # ### end Alembic commands ###
