"""add_4_url_for_artifacts

Revision ID: 43781f11dd5d
Revises: 2fc3fbeb7c6e
Create Date: 2022-08-05 10:21:52.351520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43781f11dd5d'
down_revision = '2fc3fbeb7c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('artifact_url_1', sa.String(length=300), nullable=True))
    op.add_column('piece', sa.Column('artifact_url_2', sa.String(length=300), nullable=True))
    op.add_column('piece', sa.Column('artifact_url_3', sa.String(length=300), nullable=True))
    op.add_column('piece', sa.Column('artifact_url_4', sa.String(length=300), nullable=True))
    op.drop_column('piece', 'artifact_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('artifact_url', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('piece', 'artifact_url_4')
    op.drop_column('piece', 'artifact_url_3')
    op.drop_column('piece', 'artifact_url_2')
    op.drop_column('piece', 'artifact_url_1')
    # ### end Alembic commands ###
