"""add_twitter_id_to_participants_table

Revision ID: 89a4e6d8abd8
Revises: 42fc0ab5fbbe
Create Date: 2022-08-02 23:57:34.721883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a4e6d8abd8'
down_revision = '42fc0ab5fbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('twitter_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'twitter_id')
    # ### end Alembic commands ###
