"""upgrade piece model

Revision ID: 9f7e6800667a
Revises: 89a4e6d8abd8
Create Date: 2022-08-03 18:16:59.630736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f7e6800667a'
down_revision = '89a4e6d8abd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('tweet_retweet_count', sa.Integer(), nullable=False))
    op.add_column('piece', sa.Column('tweet_reply_count', sa.Integer(), nullable=False))
    op.add_column('piece', sa.Column('tweet_like_count', sa.Integer(), nullable=False))
    op.drop_column('piece', 'tweet_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('tweet_likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('piece', 'tweet_like_count')
    op.drop_column('piece', 'tweet_reply_count')
    op.drop_column('piece', 'tweet_retweet_count')
    # ### end Alembic commands ###
